# Generated by Django 3.2.15 on 2022-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Entwurf'), ('PUBLISHED', 'Veroeffentlicht')], default='DRAFT', max_length=20, verbose_name='Blog Status'),
        ),
    ]
