# Generated by Django 3.2.15 on 2022-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220910_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vereoffentlich am'),
        ),
    ]
